### ISSUE TITLE
please make a library!!!

### ISSUE THREAD

**Issue by Jul10l1r4** [tropicoo/zoneh#2]
I can help for this, if need

**Comment by thuandv-qtsc** [comment]
I'm having an error
-------------------------------------------
2020-09-16 10:23:27,611 - [ERROR] - [zoneh.scraper:56] - Exception during getting record
Traceback (most recent call last):
  File "/zoneh/zoneh/scraper.py", line 41, in get_archive
    data = self._get_advanced_data(record['mirror'])
  File "/zoneh/zoneh/scraper.py", line 66, in _get_advanced_data
    return self._parser.get_advanced_data(text)
  File "/zoneh/zoneh/parsers/htmlparser.py", line 166, in get_advanced_data
    return MirrorPageParser(page).get_mirror_data()
  File "/zoneh/zoneh/parsers/htmlparser.py", line 76, in get_mirror_data
    inner_1 = self._elems[const.MIRROR_PAGE_MAP['metadata_1']['index']]
IndexError: list index out of range
2020-09-16 10:23:27,611 - [ERROR] - [ProcessorThread:39] - Processor thread received error during handling scrape records
Traceback (most recent call last):
  File "/zoneh/zoneh/scraper.py", line 41, in get_archive
    data = self._get_advanced_data(record['mirror'])
  File "/zoneh/zoneh/scraper.py", line 66, in _get_advanced_data
    return self._parser.get_advanced_data(text)
  File "/zoneh/zoneh/parsers/htmlparser.py", line 166, in get_advanced_data
    return MirrorPageParser(page).get_mirror_data()
  File "/zoneh/zoneh/parsers/htmlparser.py", line 76, in get_mirror_data
    inner_1 = self._elems[const.MIRROR_PAGE_MAP['metadata_1']['index']]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zoneh/zoneh/threads/processor.py", line 35, in _run
    self._pull_records()
  File "/zoneh/zoneh/threads/processor.py", line 46, in _pull_records
    for record in self._scraper.get_archive(type_=self._arch_type):
  File "/zoneh/zoneh/scraper.py", line 57, in get_archive
    raise exc.ScraperError(err_msg)
zoneh.exceptions.ScraperError: Exception during getting record
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/zoneh/zoneh/scraper.py", line 41, in get_archive
    data = self._get_advanced_data(record['mirror'])
  File "/zoneh/zoneh/scraper.py", line 66, in _get_advanced_data
    return self._parser.get_advanced_data(text)
  File "/zoneh/zoneh/parsers/htmlparser.py", line 166, in get_advanced_data
    return MirrorPageParser(page).get_mirror_data()
  File "/zoneh/zoneh/parsers/htmlparser.py", line 76, in get_mirror_data
    inner_1 = self._elems[const.MIRROR_PAGE_MAP['metadata_1']['index']]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zoneh/zoneh/threads/processor.py", line 35, in _run
    self._pull_records()
  File "/zoneh/zoneh/threads/processor.py", line 46, in _pull_records
    for record in self._scraper.get_archive(type_=self._arch_type):
  File "/zoneh/zoneh/scraper.py", line 57, in get_archive
    raise exc.ScraperError(err_msg)
zoneh.exceptions.ScraperError: Exception during getting record

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/zoneh/zoneh/commons.py", line 18, in run
    self._run()
  File "/zoneh/zoneh/threads/processor.py", line 40, in _run
    raise exc.ProcessorError(err)
zoneh.exceptions.ProcessorError: Exception during getting record
---------------------------------------------------------------------------
Please help
