### ISSUE TITLE
Dispatch - Callback error

### ISSUE THREAD

**Issue by selimkartaal** [tropicoo/zoneh#3]
I got something like this. What am i doing wrong can you help about it? 

Traceback (most recent call last):
  File "C:\Users\Kompiter\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\dispatcher.py", line 441, in process_update
    self.dispatch_error(update, e)
  File "C:\Users\Kompiter\AppData\Local\Programs\Python\Python39\lib\site-packages\telegram\ext\dispatcher.py", line 638, in dispatch_error
    callback(update, context)
TypeError: error_handler() missing 1 required positional argument: 'error'
![Screenshot_3](https://user-images.githubusercontent.com/39308821/99405167-82ba0c80-28fd-11eb-963c-83ea6e55cd34.png)

![Screenshot_2](https://user-images.githubusercontent.com/39308821/99405166-8188df80-28fd-11eb-9186-26b892e44fc1.png)

**Comment by tropicoo** [comment]
Please downgrade `python-telegram-bot` package from 13 version to 12.8.

**Comment by selimkartaal** [comment]
Thank you man it worked :)
